#! /usr/bin/env python
# -*- codes: utf-8 -*-
import sys
from poirot.poirot import Investigation, Poirot, Case
from poirot.clients.console import ConsoleClient 

if __name__ == '__main__':
    sys.argv.pop(0)
    client = ConsoleClient()
    case = Case(sys.argv)
    investigation = Investigation()
    poirot = Poirot(client, case, investigation)
    poirot.prepare()
    poirot.investigate()
    poirot.report()